### ISSUE TITLE
Footer links style issue on Firefox

### ISSUE THREAD

**Issue by ddfreyne** [nanoc/nanoc.ws#114]
Likely related to #113.

![screen shot 2015-07-06 at 09 36 54](https://cloud.githubusercontent.com/assets/6269/8517589/abe69588-23c2-11e5-8a08-0be5bc492600.png)

**Comment by TheLonelyGhost** [comment]
Not seeing this on the latest version of the site, even using [browserstack](http://www.browserstack.com) screenshots. Perhaps the fix from #113 also fixed this issue?

What version of Firefox was used to produce the screenshot?

**Comment by ddfreyne** [comment]
This is on Firefox 39.0, and I’m still seeing the same issue.

**Comment by TheLonelyGhost** [comment]
Browserstack only supports Firefox up to version 37, so that's out of the running. I'm assuming from your prior comments/code that you're on a mac. (Ubuntu 14.04, FF 39.0 here with no issues)

Will need to dig into the CSS to see if anything seems off, but I'm not able to reproduce the issue.

**Comment by ddfreyne** [comment]
Fixed in e374eae07211ed475507c6069db7dd0a8baed824 (sorry, no PR).

Apparently, this specific containing `li` did not have enough horizontal space in Firefox to remain unbroken in this case. Giving it more space fixed the issue.
