### ISSUE TITLE
Import code font

### ISSUE THREAD

**Issue by denis-soundcloud** [nanoc/nanoc.ws#120]
The code font (Consolas) is not imported anywhere. Additionally, the fallback does not provide a bold variant.

**Comment by ddfreyne** [comment]
Fixed by 94412de3281658c7234bc764bdda390c08aaf352.

Roboto Mono is nice (up for discussion though) and more importantly, provides bold *and* italic variants, which many fonts do not.

**Comment by DaveEveritt** [comment]
Just throwing these into the mix: [Inconsalata](http://levien.com/type/myfonts/inconsolata.html) and [Anonymous Pro](http://www.marksimonson.com/fonts/view/anonymous-pro) are worth a look - and of course Adobe's [Source Code Pro](http://www.fontsquirrel.com/fonts/source-code-pro) is pretty solid. But the curly braces in [BPmono](http://www.fontsquirrel.com/fonts/BPmono) are really nice and readable too…

**Comment by ddfreyne** [comment]
* Inconsolata only has regular (missing **bold**, _italic_)
* Anonymous Pro is a font I haven’t looked at in a while. I could give this a try!
* Source Code Pro has regular an bold (missing _italic_)
* BPmono is a font I didn’t know about and will investigate!

**Comment by DaveEveritt** [comment]
Cool. Finally, [Input](http://input.fontbureau.com/) has just about everything, but is probably overkill!

**Comment by ddfreyne** [comment]
Oh, Input is actually the font I use all day. Strange that I did not think of it (probably because it’s not in Google’s web fonts directory).

**Comment by ddfreyne** [comment]
(Input is nice because it also has a condensed variant, which is nice because Source Sans is pretty condensed too.)

**Comment by DaveEveritt** [comment]
There's the [publishing licence](http://input.fontbureau.com/download/) for Input, if that's not a problem. Nice to reward typographers for their work :-)

**Comment by ddfreyne** [comment]
Hmm—the Input license would amount to $80.00/year, which I don’t think is worth it for a code font on a non-profit site.

**Comment by DaveEveritt** [comment]
Agreed. I'd be happy with your choice in the end - I just thew those others into the mix because of your "up for discussion though" comment, and because I'm a bit of a font nerd :-)
