### ISSUE TITLE
Nanoc Trello Board - Board not found

### ISSUE THREAD

**Issue by digitalfrost** [nanoc/nanoc.ws#125]
On page: 
http://nanoc.ws/contributing/

*If you have an idea for a new feature, check whether or not it’s on the nanoc Trello board yet. If it is not, start a discussion on the nanoc Google group.*

Following the link to the Trello board gives  **board not found**

**Comment by ddfreyne** [comment]
Oh, thanks for noticing. The [v4 Contributing page](http://v4.nanoc.ws/contributing/) got updated, but not the main one. Will fix.

**Comment by ddfreyne** [comment]
Fixed in 995916f8988b473c4e13981c83349b29dc59339b.
