### ISSUE TITLE
Migration guide completeness

### ISSUE THREAD

**Issue by opatry** [nanoc/nanoc.ws#131]
Hi,

I've done the migration from Nanoc 3.x to Nanoc 4.0 (thanks for this whole new version!) and faced some issues not documented in the migration guide.

----

```
NameError: uninitialized constant Nanoc3
```

This error refers to the use of `Nanoc3::Helpers::*` that must be replaced by `Nanoc::Helpers::*`.

----

```
NoMethodError: undefined method `rep_named' for #<Nanoc::ItemView:0x007fe76147fd60>
```
I was using `item.rep_named(:myrep)` for good or bad reason but it is no more available. The alternative is to use `item.reps[:myrep]` or `item.reps.fetch(:myrep)`.
I think this relates to the paragraph
> If you get a NoMethodError that you did not expect, you might be using a private API that is no longer present in Nanoc 4.0

So, it should be ok as is, just to mention it if not related to this cause.

----

```
NameError: uninitialized constant Nanoc::Int::Context::HTMLEntities
```
I didn't understood this one, in fact this might not be related to Nanoc 4, but I was using `<%= HTMLEntities.new.decode(@config[:site][:name]) %>` in an item filtered by ERB without any issue on Nanoc 3, since the migration, I had to add `require 'htmlentities'` before using it.
This "new" behavior seems logical but is surprising according to Nanoc 3 behavior.  

----

`item.raw_filename` returns an absolute path to item file in nanoc 4.x but a path relative to nanoc site root in nanoc 3.x

----

```
NoMethodError: undefined method `item' for nil:NilClass 
  0. /xxxxx/ruby/2.2.0/gems/nanoc-4.0.0/lib/nanoc/base/views/item_rep_view.rb:15:in `=='
  1. layout /article/:4:in `get_binding'
```

I was using `is_excerpt = @item_rep == @item.rep_named(:excerpt)` and it worked fine but now I have to do `is_excerpt = @item_rep.name == @item.reps[:excerpt] ? @item.reps[:excerpt].name : "".to_sym` (it seems to be a quick & dirty solution I think, tell me if there is a better solution).

The issue isn't related to `rep_named`, at first I just replaced and used `reps[:excerpt]` but the comparison was still causing the error.

**Comment by ddfreyne** [comment]
Thanks for the lengthy write-up!

---

> ```
> NameError: uninitialized constant Nanoc3
> ```
> 
> This error refers to the use of `Nanoc3::Helpers::*` that must be replaced by `Nanoc::Helpers::*`.

This is addressed by the first point of the upgrade guide:

> * Change mentions of Nanoc3 to Nanoc.

I assume that adding an example there could be useful.

---

> ```
> NoMethodError: undefined method `rep_named' for #<Nanoc::ItemView:0x007fe76147fd60>
> ```
> I was using `item.rep_named(:myrep)` for good or bad reason but it is no more available. The alternative is to use `item.reps[:myrep]` or `item.reps.fetch(:myrep)`.
> I think this relates to the paragraph
> > If you get a NoMethodError that you did not expect, you might be using a private API that is no longer present in Nanoc 4.0
> 
> So, it should be ok as is, just to mention it if not related to this cause.

Oh, `x.rep_named(y)` being replaced by `x.reps.[y]` isn’t documented. Good catch!

---

> ```
> NameError: uninitialized constant Nanoc::Int::Context::HTMLEntities
> ```
> I didn't understood this one, in fact this might not be related to Nanoc 4, but I was using `<%= HTMLEntities.new.decode(@config[:site][:name]) %>` in an item filtered by ERB without any issue on Nanoc 3, since the migration, I had to add `require 'htmlentities'` before using it.
> This "new" behavior seems logical but is surprising according to Nanoc 3 behavior.  

This might be related to the way a Gemfile is handled now. Nanoc 3 used to load the Gemfile, mimicking `bundle exec`, but Nanoc 4 no longer does that, and so either gems have to be required explicitly, or `nanoc` has to be executed with `bundle exec nanoc`. Does this explain the issue?

---

> `item.raw_filename` returns an absolute path to item file in nanoc 4.x but a path relative to nanoc site root in nanoc 3.x

That’s correct… did this cause issues for you specifically? I left it undocumented because I thought it would be an impact-free change, but maybe it’s worth mentioning explicitly.

---

> ```
> NoMethodError: undefined method `item' for nil:NilClass 
>   0. /xxxxx/ruby/2.2.0/gems/nanoc-4.0.0/lib/nanoc/base/views/item_rep_view.rb:15:in `=='
>   1. layout /article/:4:in `get_binding'
> ```
> 
> I was using `is_excerpt = @item_rep == @item.rep_named(:excerpt)` and it worked fine but now I have  to do `is_excerpt = @item_rep.name == @item.reps[:excerpt] ? @item.reps[:excerpt].name : "".to_sym` (it seems to be a quick & dirty solution I think, tell me if there is a better solution).
> 
> The issue isn't related to `rep_named`, at first I just replaced and used `reps[:excerpt]` but the comparison was still causing the error.

That’s a bug! Comparing an item rep with anything else is always going to crash, because the `#==` method doesn’t check whether the compared thing is also an item rep:

```ruby
    def ==(other)
      item.identifier == other.item.identifier && name == other.name
    end
```

By the way, a faster/nicer way of doing `is_excerpt = @item_rep == @item.rep_named(:excerpt)` is to compare the names directly, like `is_excerpt = @item_rep.name == :excerpt`.

**Comment by opatry** [comment]
> Thanks for the lengthy write-up!
> ------------------------------
>
> NameError: uninitialized constant Nanoc3
>
> This error refers to the use of Nanoc3::Helpers::* that must be replaced
> by Nanoc::Helpers::*.
>
> This is addressed by the first point of the upgrade guide:
>
>
>    - Change mentions of Nanoc3 to Nanoc.
>
> I assume that adding an example there could be useful.
>

Oh, I missed it! Maybe at least using `code` markup can improve the
visibility of this item, but the information is here.


> ------------------------------
>
> NameError: uninitialized constant Nanoc::Int::Context::HTMLEntities
>
> I didn't understood this one, in fact this might not be related to Nanoc
> 4, but I was using <%= HTMLEntities.new.decode(@config[:site][:name]) %>
> in an item filtered by ERB without any issue on Nanoc 3, since the
> migration, I had to add require 'htmlentities' before using it.
> This "new" behavior seems logical but is surprising according to Nanoc 3
> behavior.
>
> This might be related to the way a Gemfile is handled now. Nanoc 3 used to
> load the Gemfile, mimicking bundle exec, but Nanoc 4 no longer does that,
> and so either gems have to be required explicitly, or nanoc has to be
> executed with bundle exec nanoc. Does this explain the issue?
>

Hmm, so it explains the difference in behavior but I always use bundle exec
(and always did), so I'm not sure this is the issue :(


> ------------------------------
>
> item.raw_filename returns an absolute path to item file in nanoc 4.x but
> a path relative to nanoc site root in nanoc 3.x
>
> That’s correct… did this cause issues for you specifically? I left it
> undocumented because I thought it would be an impact-free change, but maybe
> it’s worth mentioning explicitly.
>

It causes an issue to me but I was doing something a little bit non
catholic I would say!
I was using something relying on file system rather than on items. I should
improve that, but still the behavior changed.
My short term fix was to use `Dir.pwd` as a workaround.


> ------------------------------
>
> NoMethodError: undefined method `item' for nil:NilClass
>   0. /xxxxx/ruby/2.2.0/gems/nanoc-4.0.0/lib/nanoc/base/views/item_rep_view.rb:15:in `=='
>   1. layout /article/:4:in `get_binding'
>
> I was using is_excerpt = @item_rep == @item.rep_named(:excerpt) and it
> worked fine but now I have to do is_excerpt = @item_rep.name ==
> @item.reps[:excerpt] ? @item.reps[:excerpt].name : "".to_sym (it seems to
> be a quick & dirty solution I think, tell me if there is a better solution).
>
> The issue isn't related to rep_named, at first I just replaced and used
> reps[:excerpt] but the comparison was still causing the error.
>
> That’s a bug! Comparing an item rep with anything else is always going to
> crash, because the #== method doesn’t check whether the compared thing is
> also an item rep:
>
>     def ==(other)
>       item.identifier == other.item.identifier && name == other.name
>     end
>
>
But, `@item_rep` and `@item.rep_named(:excerpt)` both return an `ItemRep`
isn't it?


> By the way, a faster/nicer way of doing is_excerpt = @item_rep ==
> @item.rep_named(:excerpt) is to compare the names directly, like is_excerpt
> = @item_rep.name == :excerpt.
>

Oh, yes, nicer solution! Thanks


-- 
Olivier PATRY

**Comment by ddfreyne** [comment]
> But, `@item_rep` and `@item.rep_named(:excerpt)` both return an `ItemRep`
isn't it?

Yup.

**Comment by ddfreyne** [comment]
I extracted #134 from this issue.

**Comment by ddfreyne** [comment]
Also: nanoc/nanoc#735.

**Comment by ddfreyne** [comment]
I believe I can close this issue now, since I extracted the individual issues. Let me know if I missed anything!
