### ISSUE TITLE
Markdown links in documentation

### ISSUE THREAD

**Issue by DieterDePaepe** [nanoc/nanoc.ws#172]
On page http://nanoc.ws/doc/rules/, there are multiple occurrences of markdown links that were not replaced. Eg:

    The argument for the #compile method call is a [pattern](/doc/identifiers-and-patterns/#patterns).

**Comment by ddfreyne** [comment]
Thanks for letting me know! This got lost in the conversion from Markdown to D*Mark. Fixed in a09fb4f5da69427b4f249aa0e8685a269f4f6c86 (along with a new check to make sure this doesn’t happen again).
