### ISSUE TITLE
Inconsistent use of item and @item in examples

### ISSUE THREAD

**Issue by DieterDePaepe** [nanoc/nanoc.ws#173]
In the examples (eg page http://nanoc.ws/doc/rules/), both `item` and `@item` are being used. Most likely, one is the recommended approach and the other is not?

**Comment by ddfreyne** [comment]
Both of them work. I don’t have a preference myself (hence the usage of both types on the same page), but it’s probably a good idea to clarify.

**Comment by ddfreyne** [comment]
I’ll close this one for now; both approaches work and it mostly boils down to a matter of taste.
