### ISSUE TITLE
Documentation clarifications

### ISSUE THREAD

**Issue by DieterDePaepe** [nanoc/nanoc.ws#174]
Some suggestions I have regarding the documentation (things that are/were unclear to me):
- Clarify how compile, layout and route can affect each other. It took me a while to understand why the example below wasn't working (I wanted a specific processing of files of a certain type):

```
route '/**/*.cat' do
  '/cats' + item.identifier.without_ext + ".meow"
end

#Present in starter Rules
compile '/**/*' do
  write item.identifier.to_s
end
```
Instead, I had to do:
```
route '/**/*.cat' do
  '/cats' + item.identifier.without_ext + ".meow"
end

compile '/**/*.cat' do
end

#Present in starter Rules
compile '/**/*' do
  write item.identifier.to_s
end
```
- Explicitly mention rules are triggered in order of definition, and only one rule (set of rules in case layout/route/compile) per file. At least that's how I think it works now.
- Dedicate a section to the `representation` principle, with examples. I'm not sure how/why to use it.
- Dedicate a section to the `snapshot` principle, with examples. I'm not sure how/why to use it.

**Comment by ddfreyne** [comment]
I’ve written a guide called [Creating PDFs](http://nanoc.ws/doc/guides/creating-pdfs/) which gives an example of how representations work.

There’s also the [Items](http://nanoc.ws/doc/items-and-layouts/#items) section on the site, which explains item representations and item snapshots.

**Comment by ddfreyne** [comment]
Additionally, the [Rules](http://nanoc.ws/doc/rules/) page mentions that rules are triggered in order of first match. I’m not sure how/where to make this more explicit.

**Comment by ddfreyne** [comment]
I’ve also added a tip to the Rules page to avoid mixing write + route calls.

**Comment by ddfreyne** [comment]
I’ll close this ticket now as I believe that I’ve addressed all your concerns. LMK if you would like more changes.
