### ISSUE TITLE
Document extra_files

### ISSUE THREAD

**Issue by ddfreyne** [nanoc/nanoc.ws#176]
The `extra_files` option, already in Nanoc since 3.7.5, isn’t documented.

Also see https://github.com/nanoc/nanoc/issues/754.

**Comment by connorshea** [comment]
@ddfreyne This should also be documented in the relevant dotfile Troubleshooting section, ideally :)

**Comment by connorshea** [comment]
Would you accept a PR that adds that as well as an updated Troubleshooting section?

I was having trouble figuring out how to make hidden directories work, but finally got it working with this:

In `nanoc.yaml`: `extra_files: ['.well-known/**/*']`

In `Rules`: `passthrough '/.well-known/**/*'`

**Comment by ddfreyne** [comment]
I’ve expanded the troubleshooting section so that it now mentions `extra_files`. Thanks for letting me know!

**Comment by connorshea** [comment]
Thanks :)
