### ISSUE TITLE
Document how to enable experimental features

### ISSUE THREAD

**Issue by connorshea** [nanoc/nanoc.ws#187]
I'd like to try out the profiler but I can't figure out how to do that, it'd be nice to have it documented :)

**Comment by ddfreyne** [comment]
Good point!

Quick answer: set the `NANOC_FEATURES` env var to `profiler`, or a comma-separated list that includes `profiler`, or `all` if you want to enable all experimental features.

**Comment by ddfreyne** [comment]
Not quite sure what to do with this one, as there are no experimental features in Nanoc anymore!

**Comment by ddfreyne** [comment]
Will close for the time being, or at least until there is another experimental feature.
