### ISSUE TITLE
Documentation still mentions "live" command

### ISSUE THREAD

**Issue by DieterDePaepe** [nanoc/nanoc.ws#190]
The [documentation](https://nanoc.ws/doc/reference/commands/) still lists the `live` command, although this is not recognised by nanoc.

Despite this, I was looking for a similar command. What is the recommended alternative for live updating files being edited?

**Comment by ddfreyne** [comment]
The `live` command exists, but is only available when `guard-nanoc` is in the `nanoc` section of the Gemfile (see [guard-nanoc](https://github.com/guard/guard-nanoc#installation)).

I agree that the documentation on the `live` command is unclear. Will fix!

**Comment by ddfreyne** [comment]
I’ve fixed this by hiding the `live` command, which makes the most sense as it’s not part of Nanoc by default.
