### ISSUE TITLE
Routing rule shown in tutorial is different than what is created via nanoc create-site tutorial

### ISSUE THREAD

**Issue by derrickaw** [nanoc/nanoc.ws#226]
Routing rule shown on tutorial page - https://nanoc.ws/doc/tutorial/ shows this:

```
route '/**/*.{html,md}' do
  if item.identifier =~ '/index.*'
    '/index.html'
  else
    item.identifier.without_ext + '/index.html'
  end
end
```

But after running "nanoc create-site tutorial" and the Rules file gets created, it shows something different.  The routing rule has been incorporated into the compilation code for html and md formated files.

```
#!/usr/bin/env ruby

compile '/index.html' do
  layout '/default.*'
  write '/index.html'
end

compile '/**/*.html' do
  layout '/default.*'
  write item.identifier.without_ext + '/index.html'
end

# This is an example rule that matches Markdown (.md) files, and filters them
# using the :kramdown filter. It is commented out by default, because kramdown
# is not bundled with Nanoc or Ruby.
#
compile '/**/*.md' do
  filter :kramdown
  layout '/default.*'
  write item.identifier.without_ext + '/index.html'
end

compile '/**/*' do
  write item.identifier.to_s
end 
```

**Comment by ddfreyne** [comment]
Good catch — the default Rules file has changed, but the site hasn’t updated to reflect that change.

(The routing rule is not part of the default Rules file anymore on purpose — compilation rules that contain `write` calls mix badly with routing rules.)

**Comment by ddfreyne** [comment]
The updated tutorial now uses the proper (new) Rules file: https://nanoc.ws/doc/tutorial/#write-pages-in-markdown
