### ISSUE TITLE
Website is down?

### ISSUE THREAD

**Issue by bluebear94** [nanoc/nanoc.ws#252]
When I visit https://nanoc.ws, it says that the page wasn't found. In addition, I got a certificate error when trying to connect.

**Comment by ddfreyne** [comment]
Ack! I migrated the DNS setup, and messed up in the process. Looking into it now.

**Comment by ddfreyne** [comment]
For now, you can use https://nanoc.netlify.app/ as a workaround.

**Comment by ddfreyne** [comment]
After the 1-hour TTL, nanoc.ws should be back up and running as usual.
