### ISSUE TITLE
Clarify how to use Sass/SCSS

### ISSUE THREAD

**Issue by ddfreyne** [nanoc/nanoc.ws#78]
Quoting @Pistos:

> It would be good if there were just one spot in the docs that said "here's everything you need to do/put to use .sass/.scss". I had to piece that all together from like 3 things spread out across the documentation, and Stackoverflow, etc.

Also see [this gist](https://gist.github.com/Pistos/b81459f031aba8622813), which contains the Rules content necessary to get Sass/SCSS working.

CC @Pistos

**Comment by bobthecow** [comment]
Wouldn't hurt to have a section of the site with a bunch of common "How to X" entries. Less, Sass/SCSS, CoffeeScript, HAML, etc.

**Comment by ddfreyne** [comment]
I’ve created a guide that describes how to use common filters: http://nanoc.ws/doc/guides/using-common-filters/.
