### ISSUE TITLE
Tutorial does not mention Bundler

### ISSUE THREAD

**Issue by ddfreyne** [nanoc/nanoc.ws#95]
Bundler is recommended for nanoc sites, yet the tutorial does not mention it at all.

Maybe it should only mention Bundler is NOTE admonitions; teaching how to use Bundler is (and should be) out of scope for the tutorial.

**Comment by TheLonelyGhost** [comment]
I think something basic such as adding `gem "nanoc", "~> 4.0.0beta2"` to your Gemfile should be enough. So long as a link to bundler's homepage or official tutorial is included near that section, it should be enough of an indicator to gloss over that topic.

**Comment by ddfreyne** [comment]
I believe this is out of scope for the tutorial. The tutorial’s goal is to get started with Nanoc easily; it shouldn’t have to teach Bundler.
